/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package personalproject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Gitu
 */
public class RegisterCoachPanel extends javax.swing.JPanel {

    /**
     * Creates new form RegisterCoachPanel
     */
    Connection con;
    ResultSet rs;
    
    public RegisterCoachPanel() {
        initComponents();
        
        myConnection();
        hideElements();
    }
    
    public void myConnection() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            String database = "jdbc:mysql://localhost:3306/ma_club";
            con = DriverManager.getConnection(database, "root", "");
            
        }
        catch (Exception ex) {
            System.out.println("Connection error! " + ex);
        }
    }
    
    private void hideElements() {
        btnSubmit.setVisible(false);
        comboDisc.setVisible(false);
        comboHours.setVisible(false);
        lblAddress.setVisible(false);
        lblDisc.setVisible(false);
        lblFname.setVisible(false);
        lblGender.setVisible(false);
        lblHours.setVisible(false);
        lblPhone.setVisible(false);
        lblRate.setVisible(false);
        lblSalary.setVisible(false);
        lblSname.setVisible(false);
        rbFemale.setVisible(false);
        rbMale.setVisible(false);
        txtAddress.setVisible(false);
        txtFname.setVisible(false);
        txtPhone.setVisible(false);
        txtRate.setVisible(false);
        txtSalary.setVisible(false);
        txtSname.setVisible(false);
    }
    
    private void showElements() {
        btnSubmit.setVisible(true);
        comboDisc.setVisible(true);
        comboHours.setVisible(true);
        lblAddress.setVisible(true);
        lblDisc.setVisible(true);
        lblFname.setVisible(true);
        lblGender.setVisible(true);
        lblHours.setVisible(true);
        lblPhone.setVisible(true);
        lblRate.setVisible(true);
        lblSalary.setVisible(true);
        lblSname.setVisible(true);
        rbFemale.setVisible(true);
        rbMale.setVisible(true);
        txtAddress.setVisible(true);
        txtFname.setVisible(true);
        txtPhone.setVisible(true);
        txtRate.setVisible(true);
        txtSalary.setVisible(true);
        txtSname.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        lblFname = new javax.swing.JLabel();
        txtFname = new javax.swing.JTextField();
        lblSname = new javax.swing.JLabel();
        txtSname = new javax.swing.JTextField();
        lblGender = new javax.swing.JLabel();
        rbMale = new javax.swing.JRadioButton();
        rbFemale = new javax.swing.JRadioButton();
        lblAddress = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        lblPhone = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        lblDisc = new javax.swing.JLabel();
        comboDisc = new javax.swing.JComboBox();
        lblEmployment = new javax.swing.JLabel();
        rbFullTime = new javax.swing.JRadioButton();
        rbContract = new javax.swing.JRadioButton();
        lblSalary = new javax.swing.JLabel();
        txtSalary = new javax.swing.JTextField();
        lblHours = new javax.swing.JLabel();
        lblRate = new javax.swing.JLabel();
        txtRate = new javax.swing.JTextField();
        comboHours = new javax.swing.JComboBox();
        btnSubmit = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(100, 100));
        setPreferredSize(new java.awt.Dimension(1025, 640));

        jLabel1.setFont(new java.awt.Font("Eras Medium ITC", 0, 24)); // NOI18N
        jLabel1.setText("Register Coach");

        lblFname.setFont(new java.awt.Font("Eras Medium ITC", 0, 16)); // NOI18N
        lblFname.setText("First Name");

        lblSname.setFont(new java.awt.Font("Eras Medium ITC", 0, 16)); // NOI18N
        lblSname.setText("Surname");

        lblGender.setFont(new java.awt.Font("Eras Medium ITC", 0, 16)); // NOI18N
        lblGender.setText("Gender");

        rbMale.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbMale);
        rbMale.setFont(new java.awt.Font("Eras Medium ITC", 0, 16)); // NOI18N
        rbMale.setText("Male");

        rbFemale.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbFemale);
        rbFemale.setFont(new java.awt.Font("Eras Medium ITC", 0, 16)); // NOI18N
        rbFemale.setText("Female");

        lblAddress.setFont(new java.awt.Font("Eras Medium ITC", 0, 16)); // NOI18N
        lblAddress.setText("Address");

        lblPhone.setFont(new java.awt.Font("Eras Medium ITC", 0, 16)); // NOI18N
        lblPhone.setText("Phone Number");

        lblDisc.setFont(new java.awt.Font("Eras Medium ITC", 0, 16)); // NOI18N
        lblDisc.setText("Discipline");

        comboDisc.setFont(new java.awt.Font("Eras Medium ITC", 0, 16)); // NOI18N
        comboDisc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Taekwondo", "Karate" }));

        lblEmployment.setFont(new java.awt.Font("Eras Medium ITC", 0, 16)); // NOI18N
        lblEmployment.setText("Type of Employment");

        rbFullTime.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(rbFullTime);
        rbFullTime.setFont(new java.awt.Font("Eras Medium ITC", 0, 16)); // NOI18N
        rbFullTime.setText("Full-time");
        rbFullTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFullTimeActionPerformed(evt);
            }
        });

        rbContract.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(rbContract);
        rbContract.setFont(new java.awt.Font("Eras Medium ITC", 0, 16)); // NOI18N
        rbContract.setText("Contract");
        rbContract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbContractActionPerformed(evt);
            }
        });

        lblSalary.setFont(new java.awt.Font("Eras Medium ITC", 0, 16)); // NOI18N
        lblSalary.setText("Salary");

        lblHours.setFont(new java.awt.Font("Eras Medium ITC", 0, 16)); // NOI18N
        lblHours.setText("Hours");

        lblRate.setFont(new java.awt.Font("Eras Medium ITC", 0, 16)); // NOI18N
        lblRate.setText("Rate");

        comboHours.setFont(new java.awt.Font("Eras Medium ITC", 0, 16)); // NOI18N
        comboHours.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));

        btnSubmit.setBackground(new java.awt.Color(0, 200, 65));
        btnSubmit.setFont(new java.awt.Font("Eras Medium ITC", 0, 24)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(rbContract)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblEmployment, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(rbFullTime)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDisc, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(comboDisc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtPhone))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtAddress))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblGender, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbMale, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbFemale)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFname, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtFname))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSname, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtSname, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(149, 149, 149)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblSalary, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addComponent(lblHours, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblRate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboHours, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSalary, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                            .addComponent(txtRate, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmployment, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbFullTime))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbContract)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFname, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFname, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSname, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHours, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboHours, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGender, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbMale)
                    .addComponent(txtRate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRate, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbFemale)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDisc, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboDisc, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addGap(148, 148, 148))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rbFullTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFullTimeActionPerformed
        // TODO add your handling code here:
        showElements();
        
        comboHours.setEnabled(false);
        txtRate.setEnabled(false);
    }//GEN-LAST:event_rbFullTimeActionPerformed

    private void rbContractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbContractActionPerformed
        // TODO add your handling code here:
        showElements();
        
        txtSalary.setEnabled(false);
        comboHours.setEnabled(true);
        txtRate.setEnabled(true);
    }//GEN-LAST:event_rbContractActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        try {
            if (rbFullTime.isSelected()) {
                con.close();
                myConnection();
                
                String fName, sName, gender, address, phoneNum, discipline;
                double salary;
                
                fName = txtFname.getText();
                sName = txtSname.getText();
                if (rbMale.isSelected())
                    gender = rbMale.getText();
                else
                    gender = rbFemale.getText();
                address = txtAddress.getText();
                phoneNum = txtPhone.getText();
                discipline = String.valueOf(comboDisc.getSelectedItem());
                salary = Double.parseDouble(txtSalary.getText());
                
                SalaryCoach ftCoach = new SalaryCoach(fName, sName, gender, address, phoneNum, discipline, salary);

                String newrow = "INSERT INTO `coaches`(`fname`, `sname`, `gender`, "
                        + "`address`, `phone`, `discipline`, `salary`) VALUES (?,?,?,?,?,?,?)";
                PreparedStatement p = con.prepareStatement(newrow);
                p.setString(1, fName);
                p.setString(2, sName);
                p.setString(3, gender);
                p.setString(4, address);
                p.setString(5, phoneNum);
                p.setString(6, discipline);
                p.setDouble(7, ftCoach.getEarnings());
                int updatedRows = p.executeUpdate();
                if (updatedRows > 0)
                    JOptionPane.showMessageDialog(null, "Record Saved Successfully!");
                else
                    JOptionPane.showMessageDialog(null, "Error! Unable to add.");
                con.close();
                
                //System.out.println(ftCoach);
                this.setVisible(false);
            } else {
                String fName, sName, gender, address, phoneNum, discipline;
                double hours, rate;
                
                fName = txtFname.getText();
                sName = txtSname.getText();
                if (rbMale.isSelected())
                    gender = rbMale.getText();
                else
                    gender = rbFemale.getText();
                address = txtAddress.getText();
                phoneNum = txtPhone.getText();
                discipline = String.valueOf(comboDisc.getSelectedItem());
                hours = Double.parseDouble(String.valueOf(comboHours.getSelectedItem()));
                rate = Double.parseDouble(txtRate.getText());
                
                ContrCoach ctCoach = new ContrCoach(fName, sName, gender, address, phoneNum, discipline, hours, rate);
                
                String newrow = "INSERT INTO `coaches`(`fname`, `sname`, `gender`, "
                        + "`address`, `phone`, `discipline`, `salary`) VALUES (?,?,?,?,?,?,?)";
                PreparedStatement p = con.prepareStatement(newrow);
                p.setString(1, fName);
                p.setString(2, sName);
                p.setString(3, gender);
                p.setString(4, address);
                p.setString(5, phoneNum);
                p.setString(6, discipline);
                p.setDouble(7, ctCoach.getEarnings());
                int updatedRows = p.executeUpdate();
                if (updatedRows > 0)
                    JOptionPane.showMessageDialog(null, "Record Saved Successfully!");
                else
                    JOptionPane.showMessageDialog(null, "Error! Unable to add.");
                con.close();
                
                //System.out.println(ctCoach);
                this.setVisible(false);
            }
        }
        catch (Exception ex) {
            System.out.println("Error. " + ex);
            JOptionPane.showMessageDialog(null, "Error! " + ex.getMessage());
        }
    }//GEN-LAST:event_btnSubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JComboBox comboDisc;
    private javax.swing.JComboBox comboHours;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblDisc;
    private javax.swing.JLabel lblEmployment;
    private javax.swing.JLabel lblFname;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblHours;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblRate;
    private javax.swing.JLabel lblSalary;
    private javax.swing.JLabel lblSname;
    private javax.swing.JRadioButton rbContract;
    private javax.swing.JRadioButton rbFemale;
    private javax.swing.JRadioButton rbFullTime;
    private javax.swing.JRadioButton rbMale;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtRate;
    private javax.swing.JTextField txtSalary;
    private javax.swing.JTextField txtSname;
    // End of variables declaration//GEN-END:variables
}
