/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package personalproject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Gitu
 */
public class RegisterStudentPanel extends javax.swing.JPanel {

    /**
     * Creates new form RegisterStudentPanel
     */
    Connection con;
    ResultSet rs;
    
    public RegisterStudentPanel() {
        initComponents();
        
        myConnection();
        hideElements();
    }
    
    public void myConnection() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            String database = "jdbc:mysql://localhost:3306/ma_club";
            con = DriverManager.getConnection(database, "root", "");
            
        }
        catch (Exception ex) {
            System.out.println("Connection error! " + ex);
        }
    }
    
    private void hideElements() {
        btnSubmit.setVisible(false);
        comboAge.setVisible(false);
        comboCourse.setVisible(false);
        comboKarBelt.setVisible(false);
        comboKarStyle.setVisible(false);
        comboTkBelt.setVisible(false);
        comboYear.setVisible(false);
        lblAge.setVisible(false);
        lblCourse.setVisible(false);
        lblFname.setVisible(false);
        lblGender.setVisible(false);
        lblGeup.setVisible(false);
        lblKarBelt.setVisible(false);
        lblKarStyle.setVisible(false);
        lblKyu.setVisible(false);
        lblPhone.setVisible(false);
        lblSname.setVisible(false);
        lblTkBelt.setVisible(false);
        lblYear.setVisible(false);
        rbFemale.setVisible(false);
        rbMale.setVisible(false);
        txtFname.setVisible(false);
        txtGeup.setVisible(false);
        txtKyu.setVisible(false);
        txtPhone.setVisible(false);
        txtSname.setVisible(false);
    }
    
    private void showElements() {
        btnSubmit.setVisible(true);
        comboAge.setVisible(true);
        comboCourse.setVisible(true);
        comboKarBelt.setVisible(true);
        comboKarStyle.setVisible(true);
        comboTkBelt.setVisible(true);
        comboYear.setVisible(true);
        lblAge.setVisible(true);
        lblCourse.setVisible(true);
        lblFname.setVisible(true);
        lblGender.setVisible(true);
        lblGeup.setVisible(true);
        lblKarBelt.setVisible(true);
        lblKarStyle.setVisible(true);
        lblKyu.setVisible(true);
        lblPhone.setVisible(true);
        lblSname.setVisible(true);
        lblTkBelt.setVisible(true);
        lblYear.setVisible(true);
        rbFemale.setVisible(true);
        rbMale.setVisible(true);
        txtFname.setVisible(true);
        txtGeup.setVisible(true);
        txtKyu.setVisible(true);
        txtPhone.setVisible(true);
        txtSname.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblFname = new javax.swing.JLabel();
        txtFname = new javax.swing.JTextField();
        lblSname = new javax.swing.JLabel();
        txtSname = new javax.swing.JTextField();
        lblGender = new javax.swing.JLabel();
        rbMale = new javax.swing.JRadioButton();
        rbFemale = new javax.swing.JRadioButton();
        lblAge = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        lblCourse = new javax.swing.JLabel();
        comboCourse = new javax.swing.JComboBox();
        lblDisc = new javax.swing.JLabel();
        rbTk = new javax.swing.JRadioButton();
        rbKarate = new javax.swing.JRadioButton();
        lblGeup = new javax.swing.JLabel();
        txtKyu = new javax.swing.JTextField();
        lblKarBelt = new javax.swing.JLabel();
        lblKarStyle = new javax.swing.JLabel();
        comboAge = new javax.swing.JComboBox();
        btnSubmit = new javax.swing.JButton();
        comboKarStyle = new javax.swing.JComboBox();
        lblYear = new javax.swing.JLabel();
        comboYear = new javax.swing.JComboBox();
        comboKarBelt = new javax.swing.JComboBox();
        lblKyu = new javax.swing.JLabel();
        txtGeup = new javax.swing.JTextField();
        lblTkBelt = new javax.swing.JLabel();
        comboTkBelt = new javax.swing.JComboBox();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1025, 640));

        jLabel1.setFont(new java.awt.Font("Eras Medium ITC", 0, 24)); // NOI18N
        jLabel1.setText("Register Student");

        lblFname.setFont(new java.awt.Font("Eras Medium ITC", 0, 16)); // NOI18N
        lblFname.setText("First Name");

        lblSname.setFont(new java.awt.Font("Eras Medium ITC", 0, 16)); // NOI18N
        lblSname.setText("Surname");

        lblGender.setFont(new java.awt.Font("Eras Medium ITC", 0, 16)); // NOI18N
        lblGender.setText("Gender");

        rbMale.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(rbMale);
        rbMale.setFont(new java.awt.Font("Eras Medium ITC", 0, 16)); // NOI18N
        rbMale.setText("Male");

        rbFemale.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(rbFemale);
        rbFemale.setFont(new java.awt.Font("Eras Medium ITC", 0, 16)); // NOI18N
        rbFemale.setText("Female");

        lblAge.setFont(new java.awt.Font("Eras Medium ITC", 0, 16)); // NOI18N
        lblAge.setText("Age");

        lblPhone.setFont(new java.awt.Font("Eras Medium ITC", 0, 16)); // NOI18N
        lblPhone.setText("Phone Number");

        lblCourse.setFont(new java.awt.Font("Eras Medium ITC", 0, 16)); // NOI18N
        lblCourse.setText("Course");

        comboCourse.setFont(new java.awt.Font("Eras Medium ITC", 0, 16)); // NOI18N
        comboCourse.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "APT", "CJS", "IBA", "IR", "IST", "JRN", "PSY", "" }));

        lblDisc.setFont(new java.awt.Font("Eras Medium ITC", 0, 16)); // NOI18N
        lblDisc.setText("Discipline");

        rbTk.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbTk);
        rbTk.setFont(new java.awt.Font("Eras Medium ITC", 0, 16)); // NOI18N
        rbTk.setText("Taekwondo");
        rbTk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTkActionPerformed(evt);
            }
        });

        rbKarate.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbKarate);
        rbKarate.setFont(new java.awt.Font("Eras Medium ITC", 0, 16)); // NOI18N
        rbKarate.setText("Karate");
        rbKarate.setPreferredSize(new java.awt.Dimension(75, 37));
        rbKarate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbKarateActionPerformed(evt);
            }
        });

        lblGeup.setFont(new java.awt.Font("Eras Medium ITC", 0, 16)); // NOI18N
        lblGeup.setText("Geup");
        lblGeup.setToolTipText("Teakwondo Grade");

        lblKarBelt.setFont(new java.awt.Font("Eras Medium ITC", 0, 16)); // NOI18N
        lblKarBelt.setText("Belt");

        lblKarStyle.setFont(new java.awt.Font("Eras Medium ITC", 0, 16)); // NOI18N
        lblKarStyle.setText("Style");

        comboAge.setFont(new java.awt.Font("Eras Medium ITC", 0, 16)); // NOI18N
        comboAge.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "17", "18", "19", "20", "21", "22", "23", "24", "25" }));

        btnSubmit.setBackground(new java.awt.Color(0, 200, 65));
        btnSubmit.setFont(new java.awt.Font("Eras Medium ITC", 0, 24)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        comboKarStyle.setFont(new java.awt.Font("Eras Medium ITC", 0, 16)); // NOI18N
        comboKarStyle.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kyokushin", "Shotokan" }));

        lblYear.setFont(new java.awt.Font("Eras Medium ITC", 0, 16)); // NOI18N
        lblYear.setText("Year");

        comboYear.setFont(new java.awt.Font("Eras Medium ITC", 0, 16)); // NOI18N
        comboYear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Freshman", "Sophomore", "Junior", "Senior" }));

        comboKarBelt.setFont(new java.awt.Font("Eras Medium ITC", 0, 16)); // NOI18N
        comboKarBelt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "White", "Orange", "Orange Blue Stripe", "Blue", "Blue Green Stripe", "Yellow", "Yellow Orange Stripe", "Green", "Green Brown Stripe", "Brown", "Brown Black Stripe", "Black" }));

        lblKyu.setFont(new java.awt.Font("Eras Medium ITC", 0, 16)); // NOI18N
        lblKyu.setText("Kyu");
        lblKyu.setToolTipText("Teakwondo Grade");

        lblTkBelt.setFont(new java.awt.Font("Eras Medium ITC", 0, 16)); // NOI18N
        lblTkBelt.setText("Belt");

        comboTkBelt.setFont(new java.awt.Font("Eras Medium ITC", 0, 16)); // NOI18N
        comboTkBelt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "White", "White Striped", "Yellow", "Yellow Striped", "Green", "Green Striped", "Blue", "Blue Striped", "Red", "Red Striped", "Black" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblYear, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboYear, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(comboCourse, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtPhone))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblAge, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(comboAge, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblGender, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbMale, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbFemale)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblSname, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtSname, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblFname, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtFname))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblDisc, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbKarate, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbTk))))
                .addGap(149, 149, 149)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblGeup, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblKarBelt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblKarStyle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblTkBelt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblKyu, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboKarStyle, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtGeup)
                                .addComponent(comboTkBelt, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtKyu, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboKarBelt, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDisc, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbTk))
                .addGap(6, 6, 6)
                .addComponent(rbKarate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFname, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFname, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGeup, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGeup, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSname, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTkBelt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboTkBelt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGender, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbMale)
                    .addComponent(lblKarStyle, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboKarStyle, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbFemale)
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKyu, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKyu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAge, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboAge, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKarBelt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboKarBelt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblYear, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboYear, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 101, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1025, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rbTkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTkActionPerformed
        // TODO add your handling code here:
        showElements();

        txtGeup.setEnabled(true);
        comboTkBelt.setEnabled(true);
        comboKarStyle.setEnabled(false);
        txtKyu.setEnabled(false);
        comboKarBelt.setEnabled(false);
    }//GEN-LAST:event_rbTkActionPerformed

    private void rbKarateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbKarateActionPerformed
        // TODO add your handling code here:
        showElements();

        txtGeup.setEnabled(false);
        comboTkBelt.setEnabled(false);
        comboKarStyle.setEnabled(true);
        txtKyu.setEnabled(true);
        comboKarBelt.setEnabled(true);
    }//GEN-LAST:event_rbKarateActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        try {
            if (rbTk.isSelected()) {
                con.close();
                myConnection();
                
                String fName, sName, gender, phoneNum, course, year, geup, belt;
                int age;

                fName = txtFname.getText();
                sName = txtSname.getText();
                if (rbMale.isSelected())
                    gender = rbMale.getText();
                else
                    gender = rbFemale.getText();
                age = Integer.parseInt(String.valueOf(comboAge.getSelectedItem()));
                phoneNum = txtPhone.getText();
                course = String.valueOf(comboCourse.getSelectedItem());
                year = String.valueOf(comboYear.getSelectedItem());
                geup = txtGeup.getText();
                belt = String.valueOf(comboTkBelt.getSelectedItem());

                TKStudent tkStud = new TKStudent(fName, sName, gender, age, phoneNum, course, year, geup, belt);

                String newrow = "INSERT INTO `students`(`fname`, `sname`, `gender`, `age`, "
                        + "`phone`, `course`, `year`, `geup`, `tkbelt`) VALUES (?,?,?,?,?,?,?,?,?)";
                PreparedStatement p = con.prepareStatement(newrow);
                p.setString(1, fName);
                p.setString(2, sName);
                p.setString(3, gender);
                p.setInt(4, age);
                p.setString(5, phoneNum);
                p.setString(6, course);
                p.setString(7, year);
                p.setString(8, geup);
                p.setString(9, belt);
                int updatedRows = p.executeUpdate();
                if (updatedRows > 0)
                    JOptionPane.showMessageDialog(null, "Record Saved Successfully!");
                else
                    JOptionPane.showMessageDialog(null, "Error! Unable to add.");
                con.close();
  
                //System.out.println(tkStud);
                this.setVisible(false);
            } else {
                String fName, sName, gender, phoneNum, course, year, style, kyu, belt;
                int age;

                fName = txtFname.getText();
                sName = txtSname.getText();
                if (rbMale.isSelected())
                    gender = rbMale.getText();
                else
                    gender = rbFemale.getText();
                age = Integer.parseInt(String.valueOf(comboAge.getSelectedItem()));
                phoneNum = txtPhone.getText();
                course = String.valueOf(comboCourse.getSelectedItem());
                year = String.valueOf(comboYear.getSelectedItem());
                style = String.valueOf(comboKarStyle.getSelectedItem());
                kyu = txtKyu.getText();
                belt = String.valueOf(comboKarBelt.getSelectedItem());

                KarStudent karStud = new KarStudent(fName, sName, gender, age, phoneNum, course, year, style, kyu, belt);

                String newrow = "INSERT INTO `students`(`fname`, `sname`, `gender`, `age`, "
                        + "`phone`, `course`, `year`, `style`, "
                        + "`kyu`, `karbelt`) VALUES (?,?,?,?,?,?,?,?,?,?)";
                PreparedStatement p = con.prepareStatement(newrow);
                p.setString(1, fName);
                p.setString(2, sName);
                p.setString(3, gender);
                p.setInt(4, age);
                p.setString(5, phoneNum);
                p.setString(6, course);
                p.setString(7, year);
                p.setString(8, style);
                p.setString(9, kyu);
                p.setString(10, belt);
                int updatedRows = p.executeUpdate();
                if (updatedRows > 0)
                    JOptionPane.showMessageDialog(null, "Record Saved Successfully!");
                else
                    JOptionPane.showMessageDialog(null, "Error! Unable to add.");
                con.close();
                
                //System.out.println(karStud);
                this.setVisible(false);
            }
        }
        catch (Exception ex) {
            System.out.println("Error. " + ex);
            JOptionPane.showMessageDialog(null, "Error! " + ex.getMessage());
        }
    }//GEN-LAST:event_btnSubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox comboAge;
    private javax.swing.JComboBox comboCourse;
    private javax.swing.JComboBox comboKarBelt;
    private javax.swing.JComboBox comboKarStyle;
    private javax.swing.JComboBox comboTkBelt;
    private javax.swing.JComboBox comboYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblCourse;
    private javax.swing.JLabel lblDisc;
    private javax.swing.JLabel lblFname;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblGeup;
    private javax.swing.JLabel lblKarBelt;
    private javax.swing.JLabel lblKarStyle;
    private javax.swing.JLabel lblKyu;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblSname;
    private javax.swing.JLabel lblTkBelt;
    private javax.swing.JLabel lblYear;
    private javax.swing.JRadioButton rbFemale;
    private javax.swing.JRadioButton rbKarate;
    private javax.swing.JRadioButton rbMale;
    private javax.swing.JRadioButton rbTk;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtGeup;
    private javax.swing.JTextField txtKyu;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSname;
    // End of variables declaration//GEN-END:variables
}
