/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package personalproject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gitu
 */
public class ViewCoachesPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewCoachesPanel
     */
    Connection con;
    Statement st;
    ResultSet rs;
    
    public ViewCoachesPanel() {
        initComponents();
        
        myConnection();
        showUsers();
    }

    public void myConnection() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            String database = "jdbc:mysql://localhost:3306/ma_club";
            con = DriverManager.getConnection(database, "root", "");
            
        }
        catch (Exception ex) {
            System.out.println("Connection error! " + ex);
        }
    }
    
    public ArrayList<SalaryCoach> getUserList() {
       ArrayList<SalaryCoach> usersList = new ArrayList();
       try {
           con.close();
           myConnection();
           
           String query = "SELECT * FROM coaches";
           st = con.createStatement();
           rs = st.executeQuery(query);
           
           SalaryCoach coach;
           while (rs.next()) {
               coach = new SalaryCoach(rs.getString("fname"), rs.getString("sname"), rs.getString("gender"), 
                       rs.getString("address"), rs.getString("phone"), rs.getString("discipline"), rs.getDouble("salary"));
               usersList.add(coach);
               
           }
        }
       catch (Exception ex) {
            System.out.println("Error! " + ex);
        }
       return usersList;
    }
    
    public void showUsers() {
        ArrayList<SalaryCoach> list = getUserList();
        DefaultTableModel model = (DefaultTableModel)tblDisplayCoaches.getModel();
        
        model.setRowCount(0);
        Object[] col = new Object[7];
        for (int i=0; i<list.size(); i++) {
            col[0] = list.get(i).getFname();
            col[1] = list.get(i).getSname();
            col[2] = list.get(i).getGender();
            col[3] = list.get(i).getAddress();
            col[4] = list.get(i).getNumber();
            col[5] = list.get(i).getDisc();
            col[6] = list.get(i).getEarnings();
            model.addRow(col);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDisplayCoaches = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1025, 640));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Eras Medium ITC", 0, 36)); // NOI18N
        jLabel1.setText("Coaches");

        tblDisplayCoaches.setFont(new java.awt.Font("Eras Medium ITC", 0, 16)); // NOI18N
        tblDisplayCoaches.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Surname", "Gender", "Address", "Phone Number", "Discipline", "Salary"
            }
        ));
        tblDisplayCoaches.setRowHeight(25);
        jScrollPane1.setViewportView(tblDisplayCoaches);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1001, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDisplayCoaches;
    // End of variables declaration//GEN-END:variables
}
