/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package personalproject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Gitu
 */
public class ViewStudentsPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewStudentsPanel
     */
    Connection con;
    Statement st;
    ResultSet rs;
    
    public ViewStudentsPanel() {
        initComponents();
        
        myConnection();
        showUsers();
    }

    public void myConnection() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            String database = "jdbc:mysql://localhost:3306/ma_club";
            con = DriverManager.getConnection(database, "root", "");
            
        }
        catch (Exception ex) {
            System.out.println("Connection error! " + ex);
        }
    }
    
    public ArrayList<TKStudent> getTkList() {
       ArrayList<TKStudent> tkStudentsList = new ArrayList();
       try {
           con.close();
           myConnection();
           
           String query = "SELECT * FROM students";
           st = con.createStatement();
           rs = st.executeQuery(query);
           
           TKStudent student;
           while (rs.next()) {
               student = new TKStudent(rs.getString("fname"), rs.getString("sname"), rs.getString("gender"), 
                       rs.getInt("age"), rs.getString("phone"), rs.getString("course"), rs.getString("year"),
                       rs.getString("geup"), rs.getString("tkbelt"));
               tkStudentsList.add(student);
           }
        }
       catch (Exception ex) {
            System.out.println("Error! " + ex);
        }
       return tkStudentsList;
    }
    
    public ArrayList<KarStudent> getKarList() {
       ArrayList<KarStudent> karStudentsList = new ArrayList();
       try {
           con.close();
           myConnection();
           
           String query = "SELECT * FROM students";
           st = con.createStatement();
           rs = st.executeQuery(query);
           
           KarStudent student;
           while (rs.next()) {
               student = new KarStudent(rs.getString("fname"), rs.getString("sname"), rs.getString("gender"), 
                       rs.getInt("age"), rs.getString("phone"), rs.getString("course"), rs.getString("year"),
                       rs.getString("style"), rs.getString("kyu"), rs.getString("karbelt"));
               karStudentsList.add(student);
           }
        }
       catch (Exception ex) {
            System.out.println("Error! " + ex);
        }
       return karStudentsList;
    }
    
    public void showUsers() {
        ArrayList<TKStudent> tkList = getTkList();
        ArrayList<KarStudent> karList = getKarList();
        DefaultTableModel model = (DefaultTableModel)tblDisplayStudents.getModel();
        
        model.setRowCount(0);
        Object[] col = new Object[12];
        for (int i=0; i<tkList.size(); i++) {
            col[0] = tkList.get(i).getFname();
            col[1] = tkList.get(i).getSname();
            col[2] = tkList.get(i).getGender();
            col[3] = tkList.get(i).getAge();
            col[4] = tkList.get(i).getNumber();
            col[5] = tkList.get(i).getCourse();
            col[6] = tkList.get(i).getYear();
            col[7] = tkList.get(i).getGeup();
            col[8] = tkList.get(i).getBelt();
            col[9] = karList.get(i).getStyle();
            col[10] = karList.get(i).getKyu();
            col[11] = karList.get(i).getBelt();
            model.addRow(col);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDisplayStudents = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1025, 640));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Eras Medium ITC", 0, 36)); // NOI18N
        jLabel1.setText("Students");

        tblDisplayStudents.setFont(new java.awt.Font("Eras Medium ITC", 0, 16)); // NOI18N
        tblDisplayStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Surname", "Gender", "Age", "Phone Number", "Course", "Year", "Geup", "TKD Belt", "Karate Style", "Kyu", "Karate Belt"
            }
        ));
        tblDisplayStudents.setRowHeight(25);
        jScrollPane1.setViewportView(tblDisplayStudents);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1041, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDisplayStudents;
    // End of variables declaration//GEN-END:variables
}
